/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TimeOffRouteImport } from './routes/time-off'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminLeaveRouteImport } from './routes/admin.leave'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as AdminPositionsRouteImport } from './routes/admin.positions'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee.attendance'
import { Route as EmployeeDashboardRouteImport } from './routes/employee.dashboard'
import { Route as EmployeeHelpRouteImport } from './routes/employee.help'
import { Route as EmployeeLeaveRouteImport } from './routes/employee.leave'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee.notifications'
import { Route as EmployeePayrollRouteImport } from './routes/employee.payroll'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeSettingsRouteImport } from './routes/employee.settings'
import { Route as PayslipsIndexRouteImport } from './routes/payslips.index'
import { Route as PayslipsPayslipIdRouteImport } from './routes/payslips.$payslipId'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin.employees.index'
import { Route as AdminEmployeesEmployeeIdRouteImport } from './routes/admin.employees.$employeeId'
import { Route as AdminEmployeesNewRouteImport } from './routes/admin.employees.new'
import { Route as AdminLeaveBalancesRouteImport } from './routes/admin.leave_.balances'
import { Route as AdminPayrollAuditRouteImport } from './routes/admin.payroll_.audit'
import { Route as AdminPayrollStructuresRouteImport } from './routes/admin.payroll_.structures'
import { Route as SettingsOdooIndexRouteImport } from './routes/settings.odoo.index'
import { Route as SettingsOdooSyncRouteImport } from './routes/settings.odoo.sync'
import { Route as AdminEmployeesEmployeeIdAttendanceRouteImport } from './routes/admin.employees.$employeeId_.attendance'
import { Route as AdminEmployeesEmployeeIdLeaveRouteImport } from './routes/admin.employees.$employeeId_.leave'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeOffRoute = TimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaveRoute = AdminLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPositionsRoute = AdminPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeHelpRoute = EmployeeHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeaveRoute = EmployeeLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeePayrollRoute = EmployeePayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSettingsRoute = EmployeeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployeeRoute,
} as any)
const PayslipsIndexRoute = PayslipsIndexRouteImport.update({
  id: '/payslips/',
  path: '/payslips/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayslipsPayslipIdRoute = PayslipsPayslipIdRouteImport.update({
  id: '/payslips/$payslipId',
  path: '/payslips/$payslipId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const AdminEmployeesEmployeeIdRoute =
  AdminEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AdminEmployeesRoute,
  } as any)
const AdminEmployeesNewRoute = AdminEmployeesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const AdminLeaveBalancesRoute = AdminLeaveBalancesRouteImport.update({
  id: '/leave_/balances',
  path: '/leave/balances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollAuditRoute = AdminPayrollAuditRouteImport.update({
  id: '/payroll_/audit',
  path: '/payroll/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollStructuresRoute = AdminPayrollStructuresRouteImport.update({
  id: '/payroll_/structures',
  path: '/payroll/structures',
  getParentRoute: () => AdminRoute,
} as any)
const SettingsOdooIndexRoute = SettingsOdooIndexRouteImport.update({
  id: '/settings/odoo/',
  path: '/settings/odoo/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOdooSyncRoute = SettingsOdooSyncRouteImport.update({
  id: '/settings/odoo/sync',
  path: '/settings/odoo/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesEmployeeIdAttendanceRoute =
  AdminEmployeesEmployeeIdAttendanceRouteImport.update({
    id: '/$employeeId_/attendance',
    path: '/$employeeId/attendance',
    getParentRoute: () => AdminEmployeesRoute,
  } as any)
const AdminEmployeesEmployeeIdLeaveRoute =
  AdminEmployeesEmployeeIdLeaveRouteImport.update({
    id: '/$employeeId_/leave',
    path: '/$employeeId/leave',
    getParentRoute: () => AdminEmployeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/change-password': typeof ChangePasswordRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/time-off': typeof TimeOffRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/help': typeof AdminHelpRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leave': typeof AdminLeaveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/positions': typeof AdminPositionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/help': typeof EmployeeHelpRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/payroll': typeof EmployeePayrollRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/payslips/$payslipId': typeof PayslipsPayslipIdRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/payslips/': typeof PayslipsIndexRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/leave/balances': typeof AdminLeaveBalancesRoute
  '/admin/payroll/audit': typeof AdminPayrollAuditRoute
  '/admin/payroll/structures': typeof AdminPayrollStructuresRoute
  '/settings/odoo/sync': typeof SettingsOdooSyncRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/settings/odoo/': typeof SettingsOdooIndexRoute
  '/admin/employees/$employeeId/attendance': typeof AdminEmployeesEmployeeIdAttendanceRoute
  '/admin/employees/$employeeId/leave': typeof AdminEmployeesEmployeeIdLeaveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/time-off': typeof TimeOffRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leave': typeof AdminLeaveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/positions': typeof AdminPositionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/help': typeof EmployeeHelpRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/payroll': typeof EmployeePayrollRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/payslips/$payslipId': typeof PayslipsPayslipIdRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/payslips': typeof PayslipsIndexRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/leave/balances': typeof AdminLeaveBalancesRoute
  '/admin/payroll/audit': typeof AdminPayrollAuditRoute
  '/admin/payroll/structures': typeof AdminPayrollStructuresRoute
  '/settings/odoo/sync': typeof SettingsOdooSyncRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/settings/odoo': typeof SettingsOdooIndexRoute
  '/admin/employees/$employeeId/attendance': typeof AdminEmployeesEmployeeIdAttendanceRoute
  '/admin/employees/$employeeId/leave': typeof AdminEmployeesEmployeeIdLeaveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/change-password': typeof ChangePasswordRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/time-off': typeof TimeOffRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/help': typeof AdminHelpRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leave': typeof AdminLeaveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/positions': typeof AdminPositionsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/help': typeof EmployeeHelpRoute
  '/employee/leave': typeof EmployeeLeaveRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/payroll': typeof EmployeePayrollRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/payslips/$payslipId': typeof PayslipsPayslipIdRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/payslips/': typeof PayslipsIndexRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/employees/new': typeof AdminEmployeesNewRoute
  '/admin/leave_/balances': typeof AdminLeaveBalancesRoute
  '/admin/payroll_/audit': typeof AdminPayrollAuditRoute
  '/admin/payroll_/structures': typeof AdminPayrollStructuresRoute
  '/settings/odoo/sync': typeof SettingsOdooSyncRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/settings/odoo/': typeof SettingsOdooIndexRoute
  '/admin/employees/$employeeId_/attendance': typeof AdminEmployeesEmployeeIdAttendanceRoute
  '/admin/employees/$employeeId_/leave': typeof AdminEmployeesEmployeeIdLeaveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attendance'
    | '/change-password'
    | '/employee'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/time-off'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/help'
    | '/admin/integrations'
    | '/admin/leave'
    | '/admin/notifications'
    | '/admin/payroll'
    | '/admin/positions'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/help'
    | '/employee/leave'
    | '/employee/notifications'
    | '/employee/payroll'
    | '/employee/profile'
    | '/employee/settings'
    | '/payslips/$payslipId'
    | '/admin/'
    | '/employee/'
    | '/payslips/'
    | '/admin/employees/$employeeId'
    | '/admin/employees/new'
    | '/admin/leave/balances'
    | '/admin/payroll/audit'
    | '/admin/payroll/structures'
    | '/settings/odoo/sync'
    | '/admin/employees/'
    | '/settings/odoo/'
    | '/admin/employees/$employeeId/attendance'
    | '/admin/employees/$employeeId/leave'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/time-off'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/help'
    | '/admin/integrations'
    | '/admin/leave'
    | '/admin/notifications'
    | '/admin/payroll'
    | '/admin/positions'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/help'
    | '/employee/leave'
    | '/employee/notifications'
    | '/employee/payroll'
    | '/employee/profile'
    | '/employee/settings'
    | '/payslips/$payslipId'
    | '/admin'
    | '/employee'
    | '/payslips'
    | '/admin/employees/$employeeId'
    | '/admin/employees/new'
    | '/admin/leave/balances'
    | '/admin/payroll/audit'
    | '/admin/payroll/structures'
    | '/settings/odoo/sync'
    | '/admin/employees'
    | '/settings/odoo'
    | '/admin/employees/$employeeId/attendance'
    | '/admin/employees/$employeeId/leave'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attendance'
    | '/change-password'
    | '/employee'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/time-off'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/employees'
    | '/admin/help'
    | '/admin/integrations'
    | '/admin/leave'
    | '/admin/notifications'
    | '/admin/payroll'
    | '/admin/positions'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/settings'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/help'
    | '/employee/leave'
    | '/employee/notifications'
    | '/employee/payroll'
    | '/employee/profile'
    | '/employee/settings'
    | '/payslips/$payslipId'
    | '/admin/'
    | '/employee/'
    | '/payslips/'
    | '/admin/employees/$employeeId'
    | '/admin/employees/new'
    | '/admin/leave_/balances'
    | '/admin/payroll_/audit'
    | '/admin/payroll_/structures'
    | '/settings/odoo/sync'
    | '/admin/employees/'
    | '/settings/odoo/'
    | '/admin/employees/$employeeId_/attendance'
    | '/admin/employees/$employeeId_/leave'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  TimeOffRoute: typeof TimeOffRoute
  PayslipsPayslipIdRoute: typeof PayslipsPayslipIdRoute
  PayslipsIndexRoute: typeof PayslipsIndexRoute
  SettingsOdooSyncRoute: typeof SettingsOdooSyncRoute
  SettingsOdooIndexRoute: typeof SettingsOdooIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-off': {
      id: '/time-off'
      path: '/time-off'
      fullPath: '/time-off'
      preLoaderRoute: typeof TimeOffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leave': {
      id: '/admin/leave'
      path: '/leave'
      fullPath: '/admin/leave'
      preLoaderRoute: typeof AdminLeaveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/positions': {
      id: '/admin/positions'
      path: '/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AdminPositionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/help': {
      id: '/employee/help'
      path: '/help'
      fullPath: '/employee/help'
      preLoaderRoute: typeof EmployeeHelpRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/leave': {
      id: '/employee/leave'
      path: '/leave'
      fullPath: '/employee/leave'
      preLoaderRoute: typeof EmployeeLeaveRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/payroll': {
      id: '/employee/payroll'
      path: '/payroll'
      fullPath: '/employee/payroll'
      preLoaderRoute: typeof EmployeePayrollRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/settings': {
      id: '/employee/settings'
      path: '/settings'
      fullPath: '/employee/settings'
      preLoaderRoute: typeof EmployeeSettingsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/payslips/': {
      id: '/payslips/'
      path: '/payslips'
      fullPath: '/payslips/'
      preLoaderRoute: typeof PayslipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payslips/$payslipId': {
      id: '/payslips/$payslipId'
      path: '/payslips/$payslipId'
      fullPath: '/payslips/$payslipId'
      preLoaderRoute: typeof PayslipsPayslipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/employees/$employeeId': {
      id: '/admin/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/admin/employees/$employeeId'
      preLoaderRoute: typeof AdminEmployeesEmployeeIdRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/employees/new': {
      id: '/admin/employees/new'
      path: '/new'
      fullPath: '/admin/employees/new'
      preLoaderRoute: typeof AdminEmployeesNewRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/leave_/balances': {
      id: '/admin/leave_/balances'
      path: '/leave/balances'
      fullPath: '/admin/leave/balances'
      preLoaderRoute: typeof AdminLeaveBalancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll_/audit': {
      id: '/admin/payroll_/audit'
      path: '/payroll/audit'
      fullPath: '/admin/payroll/audit'
      preLoaderRoute: typeof AdminPayrollAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll_/structures': {
      id: '/admin/payroll_/structures'
      path: '/payroll/structures'
      fullPath: '/admin/payroll/structures'
      preLoaderRoute: typeof AdminPayrollStructuresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/settings/odoo/': {
      id: '/settings/odoo/'
      path: '/settings/odoo'
      fullPath: '/settings/odoo/'
      preLoaderRoute: typeof SettingsOdooIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/odoo/sync': {
      id: '/settings/odoo/sync'
      path: '/settings/odoo/sync'
      fullPath: '/settings/odoo/sync'
      preLoaderRoute: typeof SettingsOdooSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees/$employeeId_/attendance': {
      id: '/admin/employees/$employeeId_/attendance'
      path: '/$employeeId/attendance'
      fullPath: '/admin/employees/$employeeId/attendance'
      preLoaderRoute: typeof AdminEmployeesEmployeeIdAttendanceRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/employees/$employeeId_/leave': {
      id: '/admin/employees/$employeeId_/leave'
      path: '/$employeeId/leave'
      fullPath: '/admin/employees/$employeeId/leave'
      preLoaderRoute: typeof AdminEmployeesEmployeeIdLeaveRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
  }
}

interface AdminEmployeesRouteChildren {
  AdminEmployeesEmployeeIdRoute: typeof AdminEmployeesEmployeeIdRoute
  AdminEmployeesNewRoute: typeof AdminEmployeesNewRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminEmployeesEmployeeIdAttendanceRoute: typeof AdminEmployeesEmployeeIdAttendanceRoute
  AdminEmployeesEmployeeIdLeaveRoute: typeof AdminEmployeesEmployeeIdLeaveRoute
}

const AdminEmployeesRouteChildren: AdminEmployeesRouteChildren = {
  AdminEmployeesEmployeeIdRoute: AdminEmployeesEmployeeIdRoute,
  AdminEmployeesNewRoute: AdminEmployeesNewRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminEmployeesEmployeeIdAttendanceRoute:
    AdminEmployeesEmployeeIdAttendanceRoute,
  AdminEmployeesEmployeeIdLeaveRoute: AdminEmployeesEmployeeIdLeaveRoute,
}

const AdminEmployeesRouteWithChildren = AdminEmployeesRoute._addFileChildren(
  AdminEmployeesRouteChildren,
)

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRouteWithChildren
  AdminHelpRoute: typeof AdminHelpRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLeaveRoute: typeof AdminLeaveRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminPositionsRoute: typeof AdminPositionsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLeaveBalancesRoute: typeof AdminLeaveBalancesRoute
  AdminPayrollAuditRoute: typeof AdminPayrollAuditRoute
  AdminPayrollStructuresRoute: typeof AdminPayrollStructuresRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEmployeesRoute: AdminEmployeesRouteWithChildren,
  AdminHelpRoute: AdminHelpRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLeaveRoute: AdminLeaveRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminPositionsRoute: AdminPositionsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLeaveBalancesRoute: AdminLeaveBalancesRoute,
  AdminPayrollAuditRoute: AdminPayrollAuditRoute,
  AdminPayrollStructuresRoute: AdminPayrollStructuresRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeRouteChildren {
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeHelpRoute: typeof EmployeeHelpRoute
  EmployeeLeaveRoute: typeof EmployeeLeaveRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeePayrollRoute: typeof EmployeePayrollRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeSettingsRoute: typeof EmployeeSettingsRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeHelpRoute: EmployeeHelpRoute,
  EmployeeLeaveRoute: EmployeeLeaveRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeePayrollRoute: EmployeePayrollRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeSettingsRoute: EmployeeSettingsRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  TimeOffRoute: TimeOffRoute,
  PayslipsPayslipIdRoute: PayslipsPayslipIdRoute,
  PayslipsIndexRoute: PayslipsIndexRoute,
  SettingsOdooSyncRoute: SettingsOdooSyncRoute,
  SettingsOdooIndexRoute: SettingsOdooIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
